### ISSUE TITLE
Question about timesketch analysis plugin vs psort analysis plugins

### ISSUE THREAD

**Issue by ptitdoc** [google/timesketch#1089]
Hello,

I see there are two different kind of analysers available that can be setup using :
AUTO_INDEX_ANALYZERS = []
AUTO_SKETCH_ANALYZERS = []

In the beginning, I through INDEX analysers where referring to psort analysis plugins, but that does not seems to be the case. You also seems to be rewritting analysis plugins that are already present in psort such as sessionize.

Why rewriting some plugins that are available in psort ?

What is the difference between INDEX and SKETCH analyzers ?

**Comment by kiddinn** [comment]
OK, so there are few questions here... let me attempt to answer them:

1. **Difference between INDEX and SKETCH analyzers**

ATM there are two types of analyzers, one that works on the index. These analyzers will start as soon as a timeline gets indexed and will modify the indexed timeline. That means that if you add that particular timeline to more than one sketch you'll see the results across these sketches. These analyzers also don't have access to sketch specific actions, such as adding a new view, etc.

Sketch analyzers work on timelines that have been added to a sketch and are scoped to the sketch, they can also add views, aggregations, etc that are tied to a specific sketch.

The index analyzers will most likely be removed from the tool moving forward, but ATM we've got support for both.

2. **psort vs timesketch analyzers**

These are two very different tools, psort is part of the plaso tool and the analyzers there work on the data as it is being sorted and sent to output by psort. There each analyzer will have access to a single event as it is being sent to the output module, there is no searching, comparing across multiple timelines or anything like that. The context that you've got is the previous events that have been sent to output (so events prior to the one you are inspecting) and then the current event you are inspecting.

In timesketch the analyzers work differently, they are used after the data has been indexed. That means that each analyzer will have access to the entire timeline and can help with linking several timelines that have been added to a sketch. Timesketch also deals with data that is imported from other tools than plaso, so the analyzers can work on data that has been ingested from various processing tools.

Timesketch analyzers also have the option of extracting attributes from the events, that is one analyzer can extract URL values from message fields, or domains from a message field (or whatever the analyzer defines) and then a second analyzer can work on top of that (depend on the previous) and inspect just the data extracted by the other and then apply logic, such as statistical anomaly detection, or something like that.

psort analyzers are great for some things and timesketch analyzers for other things. They often work together, psort can annotate things timesketch can then later use, or they maybe in some cases doing similar things.

3. **The AUTO_ configurable.**

This is just a variable that you can set to automatically run certain analyzers on all ingested data. The default behavior is not to run any by default, and you'll have to manually run them in the UI or through the API (can be scripted). But in some cases you may want to always run certain analyzers (we don't want to run all of them all of the time since that will slow down the ingestion of new data)


Hopefully I've been able to answer your questions. I'm going to close down this issue, please re-open it if you feel like there are still some unanswered questions.
