### ISSUE TITLE
Export events

### ISSUE THREAD

**Issue by berggren** [google/timesketch#1106]
Need to be able to:
* export selected events
* export all events with a specific label, e.g. Starred events

**Comment by kiddinn** [comment]
do we want this to be exported just as a CSV, or is the idea to support other mechanism?

**Comment by kiddinn** [comment]
that is, do we want this to be modular, eg. story export style, or do we just want to stick to one format, either CSV or JSONL?

**Comment by jaegeral** [comment]
To add to this thing, having export for CSV and JSONL would be even better.

**Comment by kiddinn** [comment]
we already have the option in the UI to do export, which will export `all` the things...

we also have the option to use the API client to do the search, which comes back as a DataFrame, which can be easily exported into whatever format.

What is missing is really having in the UI an option after doing a search to export the results from that search.

This could be achieved using the explore API call, to add an option of `export` or `action = export` or something like that. If that option is set then the results are not sent back but instead exported (can use the same code as the other export functionality)

Maybe best to split up the export functionality into a common file, that both the export API call and the Explore one can use, that would be an easy way to support this. Then just to add some ui dust/magic to make it visible to the user.

**Comment by Passimist** [comment]
I struggle to find the option in the UI to export something for hours now. @kiddinn could you please tell me if this has to be configurated somehow? I installed the latest timesketch version following the guide. I've seen the export button in screenshots but for me its nowhere to be found.

**Comment by rocket-ops** [comment]
@Passimist, I believe currently the UI export is only available in the Dev version.

**Comment by adulau** [comment]
MISP export of

- selected events
- all events with a defined label (starred)

There is already a MISP object template for time-sketch (which can be adjusted if needed):

https://www.misp-project.org/objects.html#_timesketch_timeline

The idea would be able to share a timeline via the MISP and benefit from the timeline view in MISP. This can be done easily if a first_seen/last_seen is set for each the timesketch_timeline object for each of the exported event. As a complementary step, a relationship can be added (https://www.misp-project.org/objects.html#_relationships) such as "followed-by" and "preceding-by" which are already used by the mactime import.

**Comment by kiddinn** [comment]
> I struggle to find the option in the UI to export something for hours now. @kiddinn could you please tell me if this has to be configurated somehow? I installed the latest timesketch version following the guide. I've seen the export button in screenshots but for me its nowhere to be found.

@Passimist  Sorry for the late answer, but yes you'll need the current dev version of TS, since the release does not have that feature as of yet, we'll create a new release shortly that contains this export feature.

and @adulau ... I like that idea... I'll start developing the export function next week, and I'll make sure to have it a bit modular so that we can have an option in the API to determine formatting

**Comment by joachimmetz** [comment]
Note that MISP is licensed APGL and this can be problematic setting up a test instance for CI tests

**Comment by joachimmetz** [comment]
So https://github.com/MISP/misp-objects does not appear to have a license file but based on the [README](https://github.com/MISP/misp-objects/blob/main/README.md) it appears to be AGPL. @adulau we cannot integrate with AGPL software.

**Comment by joachimmetz** [comment]
Related https://github.com/log2timeline/plaso/issues/304

**Comment by adulau** [comment]
Thanks for the feedback. I don't get the policy as the repository won't be used per se. It's just the definition of the template.

By the way some time ago, we also relicensed the MISP taxonomies to dual-license to CC-BY-SA and BSD 2 clause license to comply with Google policies and finally the taxonomies never got used. 

Let us know if the real issue is the licensing or something else? We could again dual-license the template too...

**Comment by joachimmetz** [comment]
> Let us know if the real issue is the licensing or something else?

The real issue is the AGPL license. Unclear why you think this is not the real issue after reading the policy.

The license is designed to address the SAAS loophole (https://resources.whitesourcesoftware.com/blog-whitesource/the-saas-loophole-in-gpl-open-source-licenses). That means any organization that is providing SAAS has issues with using AGPL licensed code. 

> By the way some time ago, we also relicensed the MISP taxonomies to dual-license to CC-BY-SA and BSD 2 clause license to comply with Google policies and finally the taxonomies never got used.

The templates or Python binding can be licensed non-APGL, in the end we need to talk to the AGPL-licensed MISP core (direct or indirect). If MISP core would have a different license like CC-BY-SA and BSD 2 clause, we would have been able to integrate years ago. If you are considering re-licensing MISP core shoot me an email.

**Comment by jaegeral** [comment]
With regards to MISP export we concluded the best way moving forward would be not having a Timesketch export to MISP but a MISP module that is able to import data from the Timesketch API.

**Comment by kiddinn** [comment]
the export functionality has been added to the backend API, and hte API client has support for it, the only thing missing is the UI aspect, which is being worked on now

**Comment by kiddinn** [comment]
#1341 has the UI aspect

**Comment by kiddinn** [comment]
with both #1342 and #1343 being pushed, this can now be closed
