### ISSUE TITLE
timesketch_api_client documentation needed

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1313]
Some doc around the ts_api_client would be really helpful.

How to use the client, what can be done etc.

**Comment by berggren** [comment]
+1. Auto generated API docs are in the works and will land asap but user guide and examples would be great as well.

@kiddinn for awerness.

**Comment by jaegeral** [comment]
https://github.com/google/timesketch/pull/1318

**Comment by kiddinn** [comment]
yes, user guide is done in #1318 

But we might want to add the auto generated docs and put them on readthedocs or something like that.

**Comment by kiddinn** [comment]
this is part of #1287 , I'm going to close this issue, since the first version of the specific API client information has been documented.

There will be more, that is a notebook will be released as soon as the demo server is up and running again (the current ones updated and new ones added)

Additionall #1287 will add the sphinx generated docs to readthedocs, meaning the automatic API documentation will be completed then.
