### ISSUE TITLE
Import csv / jsonl with _id issue

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1362]
If you import a csv (most likely also jsonl) that has a column:
```_id```

You will get a sketch with zero events without any warnings or hints in celery worker.

This seems to be because the _Id value is used Timesketch internally, so if Timesketch / ES wants to give a new _id, but there is already a value, it breaks.

Expected behaviour:
- ignore that there is already a _id in the to be imported data.

**Comment by kiddinn** [comment]
The issue here is not just with the `_id` field.

The test data in question also had a `datetime` field that ES didn't support, so parsing the date field failed. Also errors from ES weren't being surfaced, so the whole thing just got ingested with no warning and no visible error messages. 

Therefore few fixes had to be added:
1. Surface ES ingestion errors
2. Fix datetime representation in the importer
3. Strip ES specific fields in the import.
