### ISSUE TITLE
deploying without docker

### ISSUE THREAD

**Issue by commandline-be** [google/timesketch#1561]
**Is your feature request related to a problem? 
for reasons of personal preference and a desire to evade cruft i'd prefer to deploy timesketch without a docker wrapped around it

**Describe the solution you'd like**
deployment script or procedure as to be able to run timesketch without docker

**Describe alternatives you've considered**
none at the time, since i don't know of an alternative to timesketch

**Additional context**
docker does not build confidence

**Comment by jaegeral** [comment]
Thx for creating that issue.

To install Timesketch without docker (which is not supported nor suggested to do) you could have a look at the docker files and run all the commands manually:

https://github.com/google/timesketch/blob/master/docker/release/build/Dockerfile-latest

There have been historic installation docs from before we used docker exclusively, but those docs might be no longer up to date and we do not maintain them.

Also you are more than welcome to provide an installation doc for your platform once you got it working.

**Comment by kiddinn** [comment]
the dockerfile jaegeral mentioned is more or less the same as a bash script, and can be easily converted to a bash script to do manual deployments if you don't want to use docker.

we have no immediate plans to support multiple methods of installation, and therefore the dockerfile will be maintained and updated, which you can then use to build up your own deployment, which should be fairly easy to do, using the scripts found in the dockerfile, since these are just commands that are issued on an Ubuntu box.
