### ISSUE TITLE
impossible to import a plaso file in timesketch

### ISSUE THREAD

**Issue by jacurutu1984** [google/timesketch#1593]
**Describe the bug**
I installed timesketch via docker as indicated on the github. I want to import a  timeline via command line. The timeline goes into the sketch and notes indexing. The indexing step never stops. While looking into the logs, I notice that there is an error message. 
psort.py: error: unrecognized arguments: --server elasticsearch --port 9200 --index_name 11b8b071c6ee42058adf15d7cbd64bf9 --elastic_mappings /etc/timesketch/plaso.mappings
**To Reproduce**
sudo docker-compose exec timesketch-web tsctl import --sketch_id 1 --file /usr/share/timesketch/upload/$file --username $username

**Expected behavior**
I expected my timeline to import in timesketch and be usable (finished indexing)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version 85.0

**Additional context**
plaso - log2timeline version 20201228
plaso - psort version 20201228
worker.log output :+1: [2021-02-06 12:41:05,280] timesketch.tasks/INFO Index timeline [K GERT IR Collection SAD51 timeline] to index [11b8b071c6ee42058adf15d7cbd64bf9] (source: plaso)
[2021-02-06 12:41:07,557] celery.redirected/WARNING /usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/loading.py:245: SAWarning: fully NULL primary key identity cannot load any object.  This condition may raise an error in a future release.
  util.warn(
[2021-02-06 12:41:07,566] timesketch.tasks/WARNING Cannot set status: No such timeline
[2021-02-06 12:41:07,567] celery.app.trace/INFO Task timesketch.lib.tasks.run_plaso[11b8b071c6ee42058adf15d7cbd64bf9] succeeded in 3.54409211800521s: 'usage: psort.py [-h] [--troubles] [-V] [--analysis PLUGIN_LIST]
                [--process_memory_limit SIZE]
                [--temporary_directory DIRECTORY] [--worker_memory_limit SIZE]
                [--worker_timeout MINUTES] [--logfile FILENAME] [-d] [-q] [-u]
                [--status_view TYPE] [--slice DATE_TIME]
                [--slice_size SLICE_SIZE] [--slicer] [--data PATH] [-a]
                [--language LANGUAGE] [--output_time_zone TIME_ZONE]
                [-o FORMAT] [-w OUTPUT_FILE] [--profilers PROFILERS_LIST]
                [--profiling_directory DIRECTORY]
                [--profiling_sample_rate SAMPLE_RATE]
                [STORAGE_FILE] [FILTER]
psort.py: error: unrecognized arguments: --server elasticsearch --port 9200 --index_name 11b8b071c6ee42058adf15d7cbd64bf9 --elastic_mappings /etc/timesketch/plaso.mappings

**Comment by kiddinn** [comment]
I assume you are using the latest timesketch, as in not the latest release but HEAD.

Although I don't see the output module being used, if `elastic_ts` is being called, then you are tracking HEAD, and it will be fixed after the weekend hopefully when the new plaso release will be added into the dev track. At that time we can update the docker instances to take advantage of plaso.

The other thing is that you are using `tsctl` to do the import. That option will soon be deprecated, I would encourage you to use the timesketch_importer to import the data rather than `tsctl`. The option to do do uploads will most likely be deprecated next week.

**Comment by kiddinn** [comment]
But if you are using the latest docker image, that is the one that is built from HEAD, then this is a Known Issue (KI) and we are working on fixing it, again which will happen next week.

And please take a look at timesketch_importer https://github.com/google/timesketch/blob/master/docs/UploadData.md#using-the-importer-cli-tool rather than `tsctl`.

**Comment by jacurutu1984** [comment]
ok thanks i will wait for next update and will take a look at timesketch importer

**Comment by jacurutu1984** [comment]
Timesketch version: 20201229

I assume it's the latest.

**Comment by kiddinn** [comment]
I'll close this for now, since this is a KI, see #1567 for updates on the progress.
