### ISSUE TITLE
Ability to query multiple sketches simultaneously from the GUI 

### ISSUE THREAD

**Issue by n0tmyproblem** [google/timesketch#1726]
**Is your feature request related to a problem? Please describe.**
The published vulnerabilities related to CVEs or recent researcher papers, can be GUI manually searched in all active sketches. This task can be difficult to achieve with many sketches.

**Describe the solution you'd like**
I propose a new tab in URL path `/supersketch` that serve similar VUE content of `/sketch/<sketch_id>/explore`, without showing the enable/disable timelines buttons and that allows the analysts to make queries to all the indices at the same time. It would save review time.

The render content table could add a static right column called "Sketch" with the name field of each matched row sketch.
The render content table could fill the columns HTML *select* list only with matched columns, not all available.

This capacity would only be available for accounts with an administrator role.

I have not delved deep enough into the code (at the moment, I wish I will can someday), but I think it would be easy to implement and would give enormous power to be able to define junior roles and a senior role that can search in all investigations.

**Describe alternatives you've considered**
Another alternative could be to add in `/sketch/<sketch_id>/explore` a checkbox "global search" that can make queries to all the sketches from an specific sketch window <sketch_id>. This solution seems unintuitive because the window show an specific sketch and the results are from any of them. Also, this option requires changes to the views and aggregates features.

**Additional context**
You could add a button just to the right of the sketch search bar, for example.

**Comment by kiddinn** [comment]
There are quite a few issues with this request.

First of all, this would be hard to maintain, ACL wise,  since you may not have access to all of the sketches, this would need to be done per sketch ACL, that means that each such query would first need to evaluate the ACL for each of the sketch, and there could be hundreds or more sketches per installation. Then this would put a lot more resource constrains on the system.

Also this goes against the design of Timesketch, which segregates each sketch as their own investigation, which is independent from other sketches.

This can obviously be achieved `easily` in the API client, in a jupyter notebook for instance

```python
result_tables = []
for sketch in ts_client.list_sketches():
  search_obj = search.Search(sketch)
  search_obj.query_string = QUERY_STRING
  # optional
  # search_obj.return_fields = 'COMMA_SEPARATED_LIST_OF_RETURN_FIELDS'
  result_tables.append(search_obj.table)
```

Or you can use a `pd.concat` to make this into a single dataframe. The `list_sketches()` does take ACLs into account, you. are only presented with the sketches you've got access to query, and then you create a separate query for each sketch, which can be easily defined aheada of time in aa constant, and then you run through each sketch...

But adding this to the REST API and then to the UI will add too many complexities and I don't think we want to add this in.
