### ISSUE TITLE
Switch search backend to OpenSearch

### ISSUE THREAD

**Issue by berggren** [google/timesketch#2084]
This issue tracks the work on switching the default search backend to OpenSearch and replacing the unmaintained Elasticsearch OSS version 7.10.2.

- [x] dev environment - change the docker-compose setup #2083 
- [x] e2e environment - change the docker-compose setup
- [x] prod environment - change the docker-compose setup
- [x] Update documentation / Migration guide (as part of documentation)

**Comment by berggren** [comment]
This has been done.

**Comment by lo0pback** [comment]
I'm getting an error when running docker-compose up:

```
WARNING: The ELASTIC_VERSION variable is not set. Defaulting to a blank string.
ERROR: no such image: docker.elastic.co/elasticsearch/elasticsearch-oss:: invalid reference format
```

This seems to be caused by line 26 in docker-compose.yml:
`image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ELASTIC_VERSION}`

Perhaps the elasticsearch container (lines 25-32) should be removed entirely? 

I also noticed that deploy_timesketch.sh was not updated like deploy_timesketch.ps1 was. It is still referencing the old elasticsearch directories and settings.
