### ISSUE TITLE
Frontent-ng Search templates: Search resets the selected timelines

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#2387]
**Describe the bug**
When a Timeline is temporary disabled an execution of a Search Template is re-activating the Timeline (all timelines) again.

**To Reproduce**
Disable a timeline
Execute a Search from a Search template

**Expected behavior**
Timeline should stay de-activated

**Screenshots**
![2387](https://user-images.githubusercontent.com/741037/197189411-8962bad3-8724-476e-ac08-3f77cc1523ef.gif)

**Comment by berggren** [comment]
I tend to agree, but it is a bit nuanced. On one end the search template is designed to reset the selected timelines because it it like starting a new search and the template can't know what timelines to operate on. On the other hand I can see the use-case for keeping the selected timelines intact so the user can continue with exploration.

It's easy to change. WDYT?
