### ISSUE TITLE
[Warning] : Storage file does not contain a metadata stream

### ISSUE THREAD

**Issue by rsh2ada** [google/timesketch#256]
I am facing an issue while parsing the plaso.dump file with psort.py. Following command i am running "psort.py -o timesketch plaso.dump". 

For every dump file, it is giving me an following error "[WARNING] (MainProcess) PID:12677 <zip_file> Storage file does not contain a metadata stream." (below screenshot for reference)
![psort_all](https://cloud.githubusercontent.com/assets/24453075/21005945/e131c278-bd5c-11e6-8a18-6a1561cc5c6d.JPG)

I believe celery worker is also running fine (below  screenshot for reference). Also timesketch server is also running fine as i am able to login and can see the Zero events are added.
![celery](https://cloud.githubusercontent.com/assets/24453075/21005762/1b70a842-bd5c-11e6-8575-3c7d0a5fca6d.JPG)

**Comment by n3x77** [comment]
Hi,

This seems to be an error with different versions of plaso. If your Storage
Container was created with plaso Version 1.4 and Timesketch now uses 1.5.1
you will get this Message because plaso 1.4 and 1.5.1 are Not compatible.

Please try to create the plaso Storage Container with the new Version . You
gab Check the Version of plaso that was used to create the Container with
pinfo.py.

Hope this will help.

Cheers,
Sven
rsh2ada <notifications@github.com> schrieb am Do. 8. Dez. 2016 um 11:14:

**Comment by rsh2ada** [comment]
Hi Sven,

I didn't realized the version compatibility issue earlier. Thanks for bringing that into my notice.

And yes, after creating the dump file with the newer version, all events were loaded in timesketch. 

Also, do you have idea how to remove the timeline entries from timesketch module where it displays all available timelines? I am aware how to remove it from a particular sketch but not able to figure out for this.

Cheers!
Adarsh

**Comment by n3x77** [comment]
Hi Adarsh,

at the moment i don't have a solution for this. At an earlier version of
timesketch, we've just deleted the elasticsearch indexes that were
connected to
the timeline. After that we modified the SQLite Database manually. But
after switching to PostgreSQL this is not that easy anymore.

We started a feature request for that, you can find the issue here:
https://github.com/google/timesketch/issues/175

Bye,
Sven

2016-12-09 7:49 GMT+01:00 rsh2ada <notifications@github.com>:

**Comment by rsh2ada** [comment]
Thanks Sven
