### ISSUE TITLE
Not able to import CSV if datetime field is last

### ISSUE THREAD

**Issue by berggren** [google/timesketch#2709]
Details TBD

**Comment by jkppr** [comment]
Since I was debugging some other topics around the CSV import and datetime fields I tried to reproduce this problem without success.

My attempt to reproduce:

1. Get a valid CSV to upload (e.g. [sigma_events.csv](https://github.com/google/timesketch/blob/master/test_tools/test_events/sigma_events.csv))
2. Open the file in an editor and move the `datetime` field to the end.
3. Upload it via the web UI.
4. All works well and I have the events as a new timeline with the correct datetime entries.

**Comment by berggren** [comment]
I can't recall where this came from, and I didn't add details to this issue. Let's close it out as not reproducable.
