### ISSUE TITLE
Support Elasticsearch 'filtered alias' as an index for timelines

### ISSUE THREAD

**Issue by maestretti** [google/timesketch#315]
A [filtered alias](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html#filtered) provides similar functionality to views in other database systems. 

If you could treat an alias as an index for purposes of creating timelines, you could leverage that for saved searches / views, as well as pre-process more generalized ES clusters. For example, we would like to be able to point Timesketch at multiple ES backends (separate issue) some of which will be used for multiple purposes (not dedicated to Timesketch). Specifically we pipe all of our CloudTrail data in to an ES cluster, if we could alias a filtered view of this data based on an IAM Profile or other identifier, and import it into a timeline along side data from Plaso that would be very helpful.

**Comment by csash** [comment]
+1 for this. We too use Timesketch with a lot of non-Plaso data. This would be awesome.

**Comment by berggren** [comment]
I have started implementing aliases (including filtered aliases). Technically this will just work with the current design because Timesketch doesn't have to care about what the alias expands to. There are a couple of caveats though:
1. Because the alias->indices expansions happens in Elasticsearch and before the search query executes we have no idea what alias was responsible for what document hit. I.e. timesketch just gets the _index back so we cannot add a custom color to the alias.
2. In the case of a single index in the alias we can use that index color. But if it is a multi index alias, what color should we present the user? The first index in the list?
3. If we have two or more aliases pointing to the same index they will get the same color and name in the UI. Is this acceptable?

**Comment by berggren** [comment]
Closing this issue as it is quite old, and a subset of this would already work in TS. We can reopen if there will be time to redesign to incorporate these ideas in the future.
