### ISSUE TITLE
Issue adding timeline

### ISSUE THREAD

**Issue by mpars0ns** [google/timesketch#42]
When trying to add a timeline via add_timeline.py  I am getting the following exception:
Traceback (most recent call last):
  File "/var/www/timesketch/utils/add_timeline.py", line 113, in <module>
    sys.exit(main())
  File "/var/www/timesketch/utils/add_timeline.py", line 92, in main
    elasticsearch.put_mapping(args.index, 'plaso_event', mapping)
  File "/usr/local/lib/python2.7/dist-packages/pyelasticsearch/client.py", line 96, in decorate
    return func(*args, query_params=query_params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyelasticsearch/client.py", line 659, in put_mapping
    query_params=query_params)
  File "/usr/local/lib/python2.7/dist-packages/pyelasticsearch/client.py", line 254, in send_request
    self._raise_exception(resp, prepped_response)
  File "/usr/local/lib/python2.7/dist-packages/pyelasticsearch/client.py", line 269, in _raise_exception
    raise error_class(response.status_code, error_message)
pyelasticsearch.exceptions.ElasticHttpError: (400, u'MergeMappingException[Merge failed with failures {[Cannot update path in _timestamp value. Value is datetime path in merged mapping is missing]}]')

I recently upgraded our ES instance from 1.2 to 1.4 not sure if that is a culprit or not. Previous additions to timesketch worked fine prior to the ES upgrade. Any suggestions?

**Comment by berggren** [comment]
Hi, thanks for your report. This indeed looks like a ES issue. I have not run 1.4 myself but will test as soon as possible. Stay tuned.

**Comment by berggren** [comment]
Hi, after looking closer at this there seems to be a couple of issues, both of them due to newer versions of elasticsearch. 

1) We need to add the _timestamp mapping every time we update.
2) We now need to add the timesketch specific mapping before we populate the index with data.

Since the last big update, all interaction with the system from the command line is via the "tsctl" command installed by timesketch. add_timeline.py is therefor depricated.

I'm working on a new output plugin for plaso psort as a temporary fix for all this. After thet I will start creating a proper Plaso frontend for timesketch and add the ability to add timelines from the UI.

I will open issues for each of these steps.

Closing this issue in the meantime.

**Comment by berggren** [comment]
See issue #50 for progress of fixing this.
