### ISSUE TITLE
Show events per timeline and events per field

### ISSUE THREAD

**Issue by geekscrapy** [google/timesketch#559]
Two ideas:

1. Graph showing amount of events per timeline
2. A graph that shows the number of events per given fields - e.g. I do a search, then in the graph view I can provide field values and it shows the number of events per field. Be great for discovering lots of events that can be discarded instantly.

**Comment by berggren** [comment]
Hey @geekscrapy,

Great ideas! We actually had #2 before but removed it due to some usability issues. I have always wanted to surface this data though so I'll start thinking about a solution.

Regarding #1: I have plans for showing this data in the timeline picker view, so you can quickly see it there. We could also do a bar graph if that is desired.

**Comment by geekscrapy** [comment]
Re 1, i think this would be best viewed in the graph personally. That's where is expect to find it

Re 2, great, this would allow you to dump a lot more data into the system and search/filter it accordingly. Not trying to make it a log destination, but some tools output more data than I would want...

**Comment by berggren** [comment]
related #193

**Comment by berggren** [comment]
This has been implemented.
