### ISSUE TITLE
More efficient tables for the results

### ISSUE THREAD

**Issue by MariasStory** [google/timesketch#786]
Hi, please implement more efficient tables for the results. One reference to start with:
https://github.com/fulmicoton/fattable

**Comment by kiddinn** [comment]
can you be more specific? What is not efficient enough and how would you like to see them?

**Comment by MariasStory** [comment]
I tried to show ~5000 entries and it took a lot of time. The problem was in the table rendering. This can be avoided and any number of events can be loaded at ones. Also, a client side cashing and refining of the search results would give additional boost in user experience.

**Comment by berggren** [comment]
We have explored infinite scroll before and we found it to be an interesting approach but also not optimal from a user experience pov. It breaks ctrl-f and other well understood actions. Can you elaborate more on why you need to scroll through that many events instead of adding filters to get the amount of events down?

I usually find it better to get a smaller, more targeted result set to analyze. But I would be really interested in hearing your use-case.

That being said, the filters need to be better and more interactive, but we should track that in a separate bug.

**Comment by kiddinn** [comment]
gentle ping on this, can you further elaborate on what you are needing?

**Comment by MariasStory** [comment]
Hi @kiddinn, thanks for following this request.
I just want to make sure that even a lot of entries >5000 can be retrieved and viewed, if needed. In browser, table rendering of all the events at ones takes too much time.

**Comment by kiddinn** [comment]
I'm assigning this to @berggren since this is a UI FR, this is implemented using python pandas in the API client, providing an efficient table structure to work with.

**Comment by berggren** [comment]
@MariasStory please provide more details on how you want this to be presented in the UI. We have both pagination support to support up to 10k events. And if you need to do anything outside of the UI we have a full featured API client as well.

what would be an alternative to the provided table view?

**Comment by berggren** [comment]
Closing this out. See comment above for rational.
