### ISSUE TITLE
Event list pagination

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#83]
If a search yields > 500 results, only the first (oldest) 500 results are displayed in the explore view without an easy way to page through the next batch of results. The end goal can be achieved by taking the last date/time and using that as Start date in the Time range filter but ideally a way (button etc.) at the top/bottom of the events results would be more ideal.

**Comment by berggren** [comment]
Pushing this to after the release.

**Comment by aarontp** [comment]
Maybe instead of full pagination we could add links to add a filter setting the min time of the last event on the page (or a max time of the first event on the page).  This would probably be relatively easy to implement.  Infinite scroll would also be pretty nice, but much more of a nice to have, :).

**Comment by aarontp** [comment]
(Oh, I just realized that the initial report mentioned this as well, so just consider this a :+1: )

**Comment by adamjnichols** [comment]
Addressed in #541

**Comment by adamjnichols** [comment]
Merged.
