### ISSUE TITLE
LDAP auth

### ISSUE THREAD

**Issue by garanews** [google/timesketch#905]
What do you think about LDAP to authenticate users (keeping managing permission in postgresql)?

**Comment by garanews** [comment]
@kiddinn @berggren would you like we have a look the code in order to implement it?

**Comment by kiddinn** [comment]
we (@berggren and me) were just discussing this the other day.

Do you think there are enough people that would benefit from a LDAP support in order to have it make sense?

There are few libraries/extensions to flask that would support it:

 - https://flask-ldap.readthedocs.io/en/latest/
 - https://pypi.org/project/Flask-LDAPConn/
 - https://flask-simpleldap.readthedocs.io/en/latest/

(at least these)

Would have to look at which one makes most sense and start experimenting with it, if it is worth the time to implement, that is if we see some users that would benefit from such an integration.

**Comment by hanej** [comment]
Yes, please!

**Comment by jaegeral** [comment]
There has not been much progress on this issue, moving it to the "future" milestone for now, if there is new interest / contributions, we can change that.

**Comment by berggren** [comment]
Closing this. To support LDAP authn I recommend using a auth proxy in front of the Timesketch server.
