### ISSUE TITLE
Easy navigation to end of timeline

### ISSUE THREAD

**Issue by aarontp** [google/timesketch#921]
Due to the size limit (10k) of the query result set, it makes it difficult to easily get to the end of the entire timeline without playing with date filters and re-running the query (potentially several times).   Maybe there's a better way to do this, but it would be nice if there was a way to do this directly in the UI.  Thanks!

**Comment by kiddinn** [comment]
This can be done using the API Client and the use of jupyter/colab, since you can load up the entire result and then do sorting/filtering on the returned data.

However, @berggren is rolling out the new UI and this is part of the discussions about how the new ui behaves.

Marking this as a FR and assigning to johan.

**Comment by berggren** [comment]
With the new UI, you can just reverse the order of the timeline and get the newest events first, then paginate "backwards" from that. Let me know if this isn't sufficiant.

I'll close out in the mean time.
