### ISSUE TITLE
.CSV file not loading timeline 

### ISSUE THREAD

**Issue by joeshmoe189** [google/timesketch#926]
Hello all, 

I'm quite new at this so I'm not sure how to word it. But when I log into timesketch using the steps from the setup guide I am able to upload a .csv into the tool but it will load indefinitely regardless of the size. Where should I look to correct this issue? and/or what do I need to help someone help me?

**Comment by n3x77** [comment]
You need to setup Celery and Redis.

The import of the json and csv Files will be handled there.



joeshmoe189 <notifications@github.com> schrieb am Di. 9. Juli 2019 um 16:58:

**Comment by joeshmoe189** [comment]
Could you point me to some documentation for reference? Also, thank you for the quick response

**Comment by joeshmoe189** [comment]
Could you point me to some documentation for reference? Also, thank you for the quick response @n3x77

**Comment by n3x77** [comment]
Hi, you're welcome...

I created an ansible role for the installation of timesketch with redis and
celery. You can find the role here
https://github.com/n3x77/ansible_timesketch/blob/master/roles/timesketch_latest/tasks/ubuntu.yml
.

I am currently updating the role to work with the newest version of
timesketch. Maybe even if you're not familiar with ansible the the steps
you have to execute can be picked up from the file. The main part is that
celery needs permissions to read your /etc/timesketch.conf file and that
you must create some tmpfiles so that after the reboot of the system the
celery worker can create some files. At first try to follow the celery
steps from the ansible file. If you need further help, I can send you some
additional steps.

joeshmoe189 <notifications@github.com> schrieb am Di., 9. Juli 2019, 17:12:

**Comment by joeshmoe189** [comment]
Hello, again @n3x77 if you happen to have the steps needed for the setup celery. I followed the ansible file (running into a ton of errors but worked through them) and my time sketch is still now loaded. But after a file is "uploaded" it will never finish

**Comment by garanews** [comment]
Hi @joeshmoe189 ,
did you read https://github.com/google/timesketch/blob/master/docs/EnablePlasoUpload.md
setup celery is quite simple from there.

**Comment by kiddinn** [comment]
is this still an issue?

**Comment by kiddinn** [comment]
ok, closing this one then, please re-open if this continues to be an issue
