### ISSUE TITLE
Error when trying to upload timeline with tsctl 

### ISSUE THREAD

**Issue by nnyx7** [google/timesketch#933]
I have the following error message after running the command:
tsctl import -f /usr/local/src/timesketch/registrar.plaso --username dev
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: a bytes-like object is required, not 'NoneType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/tsctl", line 11, in <module>
    load_entry_point('timesketch', 'console_scripts', 'tsctl')()
  File "/usr/local/src/timesketch/timesketch/tsctl.py", line 445, in main
    shell_manager.run()
  File "/usr/local/lib/python3.6/dist-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.6/dist-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/src/timesketch/timesketch/tsctl.py", line 361, in run
    timeline_name = codecs.decode(timeline_name, 'utf-8')
TypeError: <timesketch.tsctl.ImportTimeline object at 0x7f2a4fa60048>: decoding with 'utf-8' codec failed (TypeError: a bytes-like object is required, not 'NoneType')
```

**Comment by n3x77** [comment]
Hi, 

how did you install timesketch and  which version do you use?
@berggren I think this error also occurs when you try to add a new user in timesketch.

I tried to figure out what the problem is and it seems like this is an error in Timesketch Version 20190207 (last release version) if you install timesketch in an python 3 environment. 

If I use this version and install it in an python2 environment it will work like charm.

The problem between python2 and python3 is, that the new plaso version 20190709 needs a python3 environment, otherwise psort.py has not the ability to export into timesketch (disabled module).

If I use the lastest version from the master branch, I can add timelines and also users in timesketch with out the encoding errors.

**Comment by garanews** [comment]
Hello @nnyx7 ,
I am running timesketch with python3 and I solved that issue replacing some row of code in tsctl.py:

```

    # pylint: disable=arguments-differ, method-hidden
    def run(self, username, password):
        """Creates the user."""
        if not password:
            password = self.get_password_from_prompt()
        if not isinstance(password, six.text_type):
            password = codecs.decode(password, 'utf-8')
        if not isinstance(username, six.text_type):
            username = codecs.decode(username, 'utf-8')
        user = User.get_or_create(username=username)
        user.set_password(plaintext=password)
        db_session.add(user)
        db_session.commit()
        sys.stdout.write('User {0:s} created/updated\n'.format(username))

```

**Comment by studiawan** [comment]
Hi @garanews, which rows did you change in tsctl.py? I face the same problem as you. 
Many thanks.

**Comment by kiddinn** [comment]
is this still an issue?

**Comment by kiddinn** [comment]
have you tried uploading using the importer?


```
pip install timesketch-import-client
timesketch_importer.py --sketch_id <ID> <FILE>
```

**Comment by berggren** [comment]
with the move to py3 this should also have been resolved. Please reopen if it is still an issue.
